cookie:
  expiry_days: 0
  key: authentication-bi-agent-key
  name: authentication-bi-agent
credentials:
  usernames:
    admin:
      email: admin@admin.com
      name: Administrador
      password: $2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW
